apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: nginx
    tier: front-end

spec:
  template:

    metadata: 
      name: ngnix-2
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx

  replicas: 3 
  selector:
    matchLabels:
      type: myapp